/*
 Copyright 2011 Anton Kraievoy akraievoy@gmail.com
 This file is part of Holonet.

 Holonet is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 Holonet is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with Holonet. If not, see <http://www.gnu.org/licenses/>.
 */

package org.akraievoy.base.runner.swing;

import javax.swing.*;
import java.awt.*;

public class ExperimentChooserPanel {
  protected JButton closeButton;
  protected JButton launchButton;
  protected JTable experimentTable;
  protected JPanel rootPanel;
  protected JTextPane outputPane;
  protected JComboBox confCombo;
  protected JTabbedPane tabPane;
  protected JTable runsTable;
  protected JButton selectButton;
  protected JButton importButton;
  protected JTextField chainTextField;
  protected JButton chainButton;
  protected JLabel expNameLabel;
  protected JTable table1;
  protected JButton sliceButton;
  protected JTable table2;
  protected JButton computeButton;
  protected JComboBox comboBox1;

  public JPanel getRootPanel() {
    return rootPanel;
  }

  public JButton getCloseButton() {
    return closeButton;
  }

  public JTable getExperimentTable() {
    return experimentTable;
  }

  public JButton getLaunchButton() {
    return launchButton;
  }

  public JTextPane getOutputPane() {
    return outputPane;
  }

  public JComboBox getConfCombo() {
    return confCombo;
  }

  public JButton getChainButton() {
    return chainButton;
  }

  public JTextField getChainTextField() {
    return chainTextField;
  }

  public JButton getImportButton() {
    return importButton;
  }

  public JTable getRunsTable() {
    return runsTable;
  }

  public JButton getSelectButton() {
    return selectButton;
  }

  public JTabbedPane getTabPane() {
    return tabPane;
  }

  public JLabel getExpNameLabel() {
    return expNameLabel;
  }

  {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
    $$$setupUI$$$();
  }

  /**
   * Method generated by IntelliJ IDEA GUI Designer
   * >>> IMPORTANT!! <<<
   * DO NOT edit this method OR call it in your code!
   *
   * @noinspection ALL
   */
  private void $$$setupUI$$$() {
    rootPanel = new JPanel();
    rootPanel.setLayout(new BorderLayout(0, 0));
    final JPanel panel1 = new JPanel();
    panel1.setLayout(new BorderLayout(0, 0));
    rootPanel.add(panel1, BorderLayout.SOUTH);
    final JPanel panel2 = new JPanel();
    panel2.setLayout(new FlowLayout(FlowLayout.CENTER, 6, 5));
    panel1.add(panel2, BorderLayout.EAST);
    closeButton = new JButton();
    closeButton.setActionCommand("close");
    closeButton.setLabel("Close");
    closeButton.setText("Close");
    closeButton.setToolTipText("Close the runner");
    panel2.add(closeButton);
    final JLabel label1 = new JLabel();
    label1.setAlignmentX(0.25f);
    label1.setEnabled(false);
    label1.setFocusable(false);
    label1.setFont(new Font(label1.getFont().getName(), Font.ITALIC, label1.getFont().getSize()));
    label1.setForeground(new Color(-16777216));
    label1.setHorizontalAlignment(0);
    label1.setOpaque(false);
    label1.setText("(c) Anton Kraievoy, 2009");
    label1.setVerifyInputWhenFocusTarget(true);
    panel1.add(label1, BorderLayout.CENTER);
    final JPanel panel3 = new JPanel();
    panel3.setLayout(new GridBagLayout());
    panel1.add(panel3, BorderLayout.NORTH);
    tabPane = new JTabbedPane();
    rootPanel.add(tabPane, BorderLayout.CENTER);
    final JPanel panel4 = new JPanel();
    panel4.setLayout(new BorderLayout(0, 0));
    tabPane.addTab("Experiments", panel4);
    final JScrollPane scrollPane1 = new JScrollPane();
    panel4.add(scrollPane1, BorderLayout.CENTER);
    experimentTable = new JTable();
    scrollPane1.setViewportView(experimentTable);
    final JPanel panel5 = new JPanel();
    panel5.setLayout(new FlowLayout(FlowLayout.RIGHT, 12, 8));
    panel4.add(panel5, BorderLayout.SOUTH);
    importButton = new JButton();
    importButton.setText("Import");
    panel5.add(importButton);
    selectButton = new JButton();
    selectButton.setText("Select");
    panel5.add(selectButton);
    final JPanel panel6 = new JPanel();
    panel6.setLayout(new BorderLayout(0, 0));
    tabPane.addTab("Configure", panel6);
    final JScrollPane scrollPane2 = new JScrollPane();
    panel6.add(scrollPane2, BorderLayout.CENTER);
    runsTable = new JTable();
    scrollPane2.setViewportView(runsTable);
    final JPanel panel7 = new JPanel();
    panel7.setLayout(new GridBagLayout());
    panel6.add(panel7, BorderLayout.SOUTH);
    final JLabel label2 = new JLabel();
    label2.setText("Cache Chaning:");
    GridBagConstraints gbc;
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 1;
    gbc.anchor = GridBagConstraints.EAST;
    gbc.insets = new Insets(2, 2, 2, 2);
    panel7.add(label2, gbc);
    chainTextField = new JTextField();
    chainTextField.setColumns(12);
    gbc = new GridBagConstraints();
    gbc.gridx = 2;
    gbc.gridy = 1;
    gbc.weightx = 0.875;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    gbc.insets = new Insets(2, 2, 2, 2);
    panel7.add(chainTextField, gbc);
    chainButton = new JButton();
    chainButton.setText("Chain");
    chainButton.setToolTipText("Chain on selected run data");
    gbc = new GridBagConstraints();
    gbc.gridx = 3;
    gbc.gridy = 1;
    gbc.gridwidth = 3;
    gbc.anchor = GridBagConstraints.WEST;
    gbc.insets = new Insets(2, 2, 2, 2);
    panel7.add(chainButton, gbc);
    final JLabel label3 = new JLabel();
    label3.setText("Config:");
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 2;
    gbc.anchor = GridBagConstraints.EAST;
    gbc.insets = new Insets(2, 4, 2, 2);
    panel7.add(label3, gbc);
    confCombo = new JComboBox();
    gbc = new GridBagConstraints();
    gbc.gridx = 2;
    gbc.gridy = 2;
    gbc.weightx = 0.875;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    gbc.insets = new Insets(2, 2, 2, 2);
    panel7.add(confCombo, gbc);
    launchButton = new JButton();
    launchButton.setActionCommand("launch");
    launchButton.setEnabled(false);
    launchButton.setFont(new Font(launchButton.getFont().getName(), Font.BOLD, launchButton.getFont().getSize()));
    launchButton.setLabel("Launch");
    launchButton.setText("Launch");
    launchButton.setToolTipText("Launch the selected configuration");
    gbc = new GridBagConstraints();
    gbc.gridx = 5;
    gbc.gridy = 3;
    gbc.insets = new Insets(2, 2, 4, 4);
    panel7.add(launchButton, gbc);
    final JPanel spacer1 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 4;
    gbc.gridy = 3;
    gbc.weightx = 0.125;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    panel7.add(spacer1, gbc);
    final JPanel spacer2 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 3;
    gbc.weightx = 0.125;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    panel7.add(spacer2, gbc);
    final JLabel label4 = new JLabel();
    label4.setText("Experiment:");
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 0;
    gbc.anchor = GridBagConstraints.EAST;
    gbc.insets = new Insets(4, 4, 2, 2);
    panel7.add(label4, gbc);
    expNameLabel = new JLabel();
    expNameLabel.setHorizontalAlignment(2);
    expNameLabel.setHorizontalTextPosition(2);
    expNameLabel.setRequestFocusEnabled(true);
    expNameLabel.setText(" ");
    gbc = new GridBagConstraints();
    gbc.gridx = 2;
    gbc.gridy = 0;
    gbc.gridwidth = 2;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    gbc.insets = new Insets(4, 2, 2, 2);
    panel7.add(expNameLabel, gbc);
    final JScrollPane scrollPane3 = new JScrollPane();
    scrollPane3.setBackground(new Color(-3355444));
    tabPane.addTab("Output", scrollPane3);
    outputPane = new JTextPane();
    outputPane.setBackground(new Color(-16777216));
    outputPane.setFont(new Font("Monospaced", outputPane.getFont().getStyle(), outputPane.getFont().getSize()));
    outputPane.setToolTipText("Experiment output");
    scrollPane3.setViewportView(outputPane);
    final JPanel panel8 = new JPanel();
    panel8.setLayout(new GridBagLayout());
    tabPane.addTab("Browse", panel8);
    final JScrollPane scrollPane4 = new JScrollPane();
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 1;
    gbc.weightx = 0.25;
    gbc.weighty = 1.0;
    gbc.fill = GridBagConstraints.BOTH;
    panel8.add(scrollPane4, gbc);
    table1 = new JTable();
    scrollPane4.setViewportView(table1);
    final JPanel spacer3 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 2;
    gbc.gridy = 1;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    panel8.add(spacer3, gbc);
    final JPanel spacer4 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 3;
    gbc.fill = GridBagConstraints.VERTICAL;
    panel8.add(spacer4, gbc);
    sliceButton = new JButton();
    sliceButton.setText("Slice");
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 2;
    gbc.anchor = GridBagConstraints.EAST;
    panel8.add(sliceButton, gbc);
    final JSplitPane splitPane1 = new JSplitPane();
    splitPane1.setDividerLocation(180);
    splitPane1.setDividerSize(7);
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 1;
    gbc.weightx = 0.75;
    gbc.weighty = 1.0;
    gbc.fill = GridBagConstraints.BOTH;
    panel8.add(splitPane1, gbc);
    final JScrollPane scrollPane5 = new JScrollPane();
    splitPane1.setLeftComponent(scrollPane5);
    table2 = new JTable();
    scrollPane5.setViewportView(table2);
    final JScrollPane scrollPane6 = new JScrollPane();
    splitPane1.setRightComponent(scrollPane6);
    final JLabel label5 = new JLabel();
    label5.setText("Graph is here");
    scrollPane6.setViewportView(label5);
    final JPanel panel9 = new JPanel();
    panel9.setLayout(new FlowLayout(FlowLayout.RIGHT, 5, 5));
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 2;
    gbc.fill = GridBagConstraints.BOTH;
    panel8.add(panel9, gbc);
    comboBox1 = new JComboBox();
    panel9.add(comboBox1);
    computeButton = new JButton();
    computeButton.setText("Compute");
    panel9.add(computeButton);
  }

  /**
   * @noinspection ALL
   */
  public JComponent $$$getRootComponent$$$() { return rootPanel; }
}
